### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by CartiB** [CartiB/myrepro#1]
@joebottoms I am stuck on part 2 my email is cbarbosa@unbc.ca. When I go to click commit this text pops up:

Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'MojoB@LAPTOP-T5I78DHF.

**Comment by joebottoms** [comment]
Hi @CartiB,

You can fix this issue by copying those two git config lines into the 'Terminal' tab in Rstudio (and changing the name and email address to your information)

The terminal tab is next to the console tab: 

![image](https://user-images.githubusercontent.com/75814598/152707694-1ea4dac7-0092-48b0-ad8c-4a0d80377120.png)

Once you do this (and hit enter in the terminal), you should be able to save, commit, and push your script successfully! This is an issue that sometimes arises for first-time users; it's just making you identify yourself on that computer.
